// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagement.Context;

#nullable disable

namespace TaskManagement.Migrations
{
    [DbContext(typeof(TaskManagementContext))]
    partial class TaskManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Model.ProfileUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfileUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "SaeedGhotbi@outlook.com",
                            FirstName = "Saeed",
                            LastName = "Ghotbi",
                            PhoneNumber = "09380883666",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "amirTarbaran@outlook.com",
                            FirstName = "Amir",
                            LastName = "Tarbaran",
                            PhoneNumber = "09154578541",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TaskManagement.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CDT")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FailedLogin")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CDT = new DateTime(2023, 10, 12, 18, 49, 17, 258, DateTimeKind.Local).AddTicks(8300),
                            FailedLogin = 0,
                            IsActive = true,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "saeed123"
                        },
                        new
                        {
                            Id = 2,
                            CDT = new DateTime(2023, 10, 12, 18, 49, 17, 258, DateTimeKind.Local).AddTicks(8315),
                            FailedLogin = 0,
                            IsActive = true,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "amir123"
                        });
                });

            modelBuilder.Entity("TaskManagement.Model.ProfileUser", b =>
                {
                    b.HasOne("TaskManagement.Model.User", "User")
                        .WithOne("ProfileUser")
                        .HasForeignKey("TaskManagement.Model.ProfileUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.Model.User", b =>
                {
                    b.Navigation("ProfileUser");
                });
#pragma warning restore 612, 618
        }
    }
}
